{{- $appname := printf "%s" (include "name" .) -}}
{{- if .Values.configfiles }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-config" $appname }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $appname }}
    appver: {{ include "k8app.labelVersion" $ | quote }}
    chart: "{{$.Chart.Name}}-{{$.Chart.Version}}"
    release: "{{ $.Release.Name }}"
    helm.sh/chart: "{{$.Chart.Name}}-{{$.Chart.Version}}"
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "-5"
data:
{{- range $key, $value := .Values.configfiles.data }}
  {{ $key }}: {{ tpl $value $ | quote }}
{{- end }}
{{- end }}

{{- if .Values.extensions }}
---
{{- range $name, $spec := .Values.extensions}}
{{- if $spec.configfiles }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ printf "%s-%s-config" $appname $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $appname }}
    appver: {{ include "k8app.labelVersion" $ | quote }}
    chart: "{{$.Chart.Name}}-{{$.Chart.Version}}"
    release: "{{ $.Release.Name }}"
    helm.sh/chart: "{{$.Chart.Name}}-{{$.Chart.Version}}"
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
    "helm.sh/hook-weight": "-5"
data:
{{- range $key, $value := $spec.configfiles.data }}
  {{ $key }}: {{ tpl $value $ | quote }}
{{- end }}
{{- end }}
{{- end }}
{{- end }}
