{{- if .Values.volume.enabled -}}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: {{ .Release.Namespace }}
  annotations: { }
  labels:
    app: {{template "name" . }}
    appver: {{ include "k8app.labelVersion" . | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    release: "{{ .Release.Name }}"
  name: {{ template "persistantClaim" .}}
spec:
  accessModes:
    {{ toYaml  .Values.volume.accessModes }}
  storageClassName: {{ template "storageClass" . }}
  resources:
    requests:
      storage: {{default "1Gi" .Values.volume.resources.requests.storage}}
{{- end -}}