{{- if and (not (empty .Values.volume.storageClass.create)) .Values.volume.enabled -}}
{{- $appname := printf "%s" (include "name" .) -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  namespace: {{ .Release.Namespace }}
  annotations: {}
  labels:
    app: {{ $appname }}
    appver: {{ include "k8app.labelVersion" . | quote }}
    chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    release: "{{ .Release.Name }}"
  name: {{ template "storageClass" . }}
provisioner: {{.Values.volume.storageClass.create.provisioner | default "kubernetes.io/aws-ebs" }}
volumeBindingMode: WaitForFirstConsumer
{{- with .Values.volume.storageClass.create.mountOptions }}
mountOptions:
  {{ toYaml . }}
{{- end }}
parameters:
  {{- if not (empty .Values.volume.storageClass.create.parameters)}}
{{toYaml .Values.volume.storageClass.create.parameters | indent 2}}
  {{ end }}
{{end }}